import { RitualProfile } from '@/types/advisor';

// Zero-external-dependency PDF print document generator per Constraint 6
export function exportRitualKitPdf(
  pujaName: string,
  deity: string,
  profile: RitualProfile,
  samagriList: string[],
  steps: string[],
  sankalpText: string,
  timingNote?: string
): boolean {
  try {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      window.print();
      return false;
    }

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>PujaCircle - Personalized Ritual Kit - ${pujaName}</title>
  <style>
    @page {
      size: A4;
      margin: 1.5cm;
    }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #231F20;
      line-height: 1.5;
      margin: 0;
      padding: 0;
    }
    .header {
      text-align: center;
      border-bottom: 2px solid #D9642C;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    .logo {
      font-size: 22px;
      font-weight: bold;
      color: #5C1A2E;
      letter-spacing: 1px;
    }
    .tagline {
      font-size: 11px;
      color: #6B6560;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .title-box {
      background: #FAF6EF;
      border: 1px solid #C9A24B;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 20px;
    }
    .title-box h1 {
      margin: 0 0 4px 0;
      font-size: 20px;
      color: #5C1A2E;
    }
    .title-box p {
      margin: 0;
      font-size: 13px;
      color: #D9642C;
      font-weight: 600;
    }
    .section {
      margin-bottom: 20px;
    }
    .section-title {
      font-size: 14px;
      font-weight: bold;
      color: #5C1A2E;
      border-bottom: 1px solid #E5E0D8;
      padding-bottom: 4px;
      margin-bottom: 10px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .sankalp-box {
      background: #FAF6EF;
      border-left: 4px solid #5C1A2E;
      padding: 12px 14px;
      font-size: 12px;
      font-style: italic;
      color: #231F20;
      line-height: 1.6;
    }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
    }
    .samagri-item {
      font-size: 12px;
      padding: 4px 0;
      border-bottom: 1px dashed #E5E0D8;
    }
    .step-item {
      font-size: 12px;
      margin-bottom: 8px;
    }
    .step-number {
      font-weight: bold;
      color: #D9642C;
      margin-right: 6px;
    }
    .profile-pill {
      display: inline-block;
      background: #EFE3C5;
      padding: 3px 8px;
      border-radius: 4px;
      font-size: 11px;
      margin-right: 8px;
      font-weight: 600;
      color: #5C1A2E;
    }
    .footer {
      margin-top: 30px;
      border-top: 1px solid #E5E0D8;
      padding-top: 10px;
      font-size: 10px;
      color: #6B6560;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">PUJACIRCLE • SANKALP ADVISOR</div>
    <div class="tagline">Personalized Vedic Ritual Preparation Kit</div>
  </div>

  <div class="title-box">
    <h1>${pujaName}</h1>
    <p>Presiding Deity: ${deity}</p>
    <div style="margin-top: 8px;">
      <span class="profile-pill">Devotee: ${profile.fullName}</span>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Personalized Devotee Sankalp Text</div>
    <div class="sankalp-box">
      ${sankalpText}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Required Sacred Samagri Checklist</div>
    <div class="grid">
      ${samagriList.map((item) => `<div class="samagri-item">☐ ${item}</div>`).join('')}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Sequential Ritual Vidhi (Step-by-Step)</div>
    ${steps
      .map(
        (step, index) => `
      <div class="step-item">
        <span class="step-number">Step ${index + 1}.</span>
        <span>${step}</span>
      </div>
    `
      )
      .join('')}
  </div>

  ${
    timingNote
      ? `
  <div class="section">
    <div class="section-title">Auspicious Timing & Tradition Note</div>
    <div class="samagri-item" style="border: none; font-style: italic;">
      ${timingNote}
    </div>
  </div>
  `
      : ''
  }

  <div class="footer">
    Generated by PujaCircle Sankalp Advisor • Authentic Vedic Traditions for Contemporary Life
  </div>
</body>
</html>
    `;

    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();

    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 250);

    return true;
  } catch {
    return false;
  }
}
